//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarmaCustomerService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarmaEntities : DbContext
    {
        public CarmaEntities()
            : base("name=CarmaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ConsumerDemographic> ConsumerDemographics { get; set; }
        public DbSet<ConsumerLogInInfo> ConsumerLogInInfoes { get; set; }
        public DbSet<ConsumerOptIn> ConsumerOptIns { get; set; }
        public DbSet<ConsumerProduct> ConsumerProducts { get; set; }
        public DbSet<ConsumerPurchaseReason> ConsumerPurchaseReasons { get; set; }
        public DbSet<ConsumerTouchPointProfile> ConsumerTouchPointProfiles { get; set; }
        public DbSet<PurchaseDynamic> PurchaseDynamics { get; set; }
    }
}
