//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarmaCustomerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumerDemographic
    {
        public System.Guid ConsumerTouchPointID { get; set; }
        public int NameTitleID { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Street { get; set; }
        public string Street2_AptNo { get; set; }
        public string City { get; set; }
        public int StateSubDivisionID { get; set; }
        public string PostCode { get; set; }
        public string Email { get; set; }
        public string PhoneHome { get; set; }
        public string PhoneMobile { get; set; }
        public string PhoneWork { get; set; }
        public int MaritalStatusID { get; set; }
        public int IncomeLevelID { get; set; }
        public int EducationID { get; set; }
        public string CultureCode { get; set; }
        public int YardSizeID { get; set; }
        public int HomeOwnershipID { get; set; }
        public Nullable<System.DateTime> DateLastEdited { get; set; }
        public int GenderID { get; set; }
    
        public virtual ConsumerTouchPointProfile ConsumerTouchPointProfile { get; set; }
        public virtual StateSubDivision StateSubDivision { get; set; }
    }
}
