//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarmaCustomerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumerLogInInfo
    {
        public System.Guid ConsumerTouchPointID { get; set; }
        public System.Guid TouchPointID { get; set; }
        public string UserID { get; set; }
        public string Password { get; set; }
        public string PasswordQuestion { get; set; }
        public string PasswordAnswer { get; set; }
        public int RecoveryQuestionID { get; set; }
        public bool IsEnabled { get; set; }
        public int NumberOfVisits { get; set; }
        public string PageJoinedFrom { get; set; }
        public string SiteReferredFrom { get; set; }
        public System.DateTime DateLastLogin { get; set; }
        public int DeWaltMemberID { get; set; }
        public string DisplayName { get; set; }
        public bool Migrated { get; set; }
        public string pwdh { get; set; }
    
        public virtual ConsumerTouchPointProfile ConsumerTouchPointProfile { get; set; }
        public virtual TouchPoint TouchPoint { get; set; }
        public virtual RecoveryQuestion RecoveryQuestion { get; set; }
    }
}
