//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarmaCustomerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumerProduct
    {
        public ConsumerProduct()
        {
            this.ProductSatisfactions = new HashSet<ProductSatisfaction>();
        }
    
        public System.Guid ConsumerProductID { get; set; }
        public System.Guid ConsumerTouchPointID { get; set; }
        public int BrandID { get; set; }
        public System.Guid TouchPointID { get; set; }
        public string ModelNumber { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> DateWarrantyExpires { get; set; }
        public Nullable<System.Guid> ProductLocationID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateEdited { get; set; }
        public Nullable<int> LikelyToRecommendProduct { get; set; }
        public Nullable<int> LikelyToPurchaseBrand { get; set; }
    
        public virtual ConsumerTouchPointProfile ConsumerTouchPointProfile { get; set; }
        public virtual PurchaseDynamic PurchaseDynamic { get; set; }
        public virtual TouchPoint TouchPoint { get; set; }
        public virtual ICollection<ProductSatisfaction> ProductSatisfactions { get; set; }
        public virtual ProductSatisfactionOld ProductSatisfactionOld { get; set; }
    }
}
