//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarmaCustomerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSatisfaction
    {
        public System.Guid ConsumerProductID { get; set; }
        public int ProductSatisfactionTypeID { get; set; }
        public System.DateTime DateSurveyCompleted { get; set; }
        public Nullable<int> LikelyToRecommendProduct { get; set; }
        public Nullable<int> LikelyToRecommendBrand { get; set; }
        public Nullable<int> LikelyToPurchaseBrand { get; set; }
        public Nullable<int> NumberOfTimesUsedID { get; set; }
        public Nullable<int> PerformanceExpectationLevelID { get; set; }
        public Nullable<int> PurchasingActivityID { get; set; }
        public Nullable<bool> ContactCustomerServiceByPhone { get; set; }
        public Nullable<bool> ContactCustomerServiceByEmail { get; set; }
        public Nullable<bool> VisitedWebSiteForProductInfo { get; set; }
        public Nullable<bool> VisitedWebSiteForProjectInfo { get; set; }
        public Nullable<bool> VisitedWebSiteForCustomerServiceInfo { get; set; }
        public Nullable<bool> VisitedWebSiteForAnyOtherReason { get; set; }
        public Nullable<bool> VisitedServiceCenter { get; set; }
        public Nullable<bool> ReceivedEmailFromBrand { get; set; }
        public Nullable<bool> DoNotRecallAny { get; set; }
        public string PositiveFeedback { get; set; }
        public string ConstructiveFeedback { get; set; }
    
        public virtual ConsumerProduct ConsumerProduct { get; set; }
    }
}
