//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarmaCustomerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseDynamic
    {
        public PurchaseDynamic()
        {
            this.ConsumerPurchaseReasons = new HashSet<ConsumerPurchaseReason>();
        }
    
        public System.Guid ConsumerProductID { get; set; }
        public Nullable<System.DateTime> OriginalDateOfPurchase { get; set; }
        public Nullable<int> PurchaseTypeID { get; set; }
        public Nullable<System.Guid> RetailerID { get; set; }
        public Nullable<int> GiftTypeID { get; set; }
        public Nullable<int> IntendedUsageID { get; set; }
    
        public virtual ConsumerProduct ConsumerProduct { get; set; }
        public virtual ICollection<ConsumerPurchaseReason> ConsumerPurchaseReasons { get; set; }
    }
}
