//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarmaCustomerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecoveryQuestion
    {
        public RecoveryQuestion()
        {
            this.ConsumerLogInInfoes = new HashSet<ConsumerLogInInfo>();
        }
    
        public int RecoveryQuestionID { get; set; }
        public string RecoveryQuestionText { get; set; }
    
        public virtual ICollection<ConsumerLogInInfo> ConsumerLogInInfoes { get; set; }
    }
}
