//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarmaCustomerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateSubDivision
    {
        public StateSubDivision()
        {
            this.ConsumerDemographics = new HashSet<ConsumerDemographic>();
        }
    
        public int StateSubDivisionID { get; set; }
        public string StateSubDivisionFullName { get; set; }
        public string StateSubDivisionAbbreviation { get; set; }
        public int CountryID { get; set; }
    
        public virtual ICollection<ConsumerDemographic> ConsumerDemographics { get; set; }
    }
}
